# Generated by Django 4.2.6 on 2023-10-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='name',
            new_name='title',
        ),
    ]
